### ISSUE TITLE
NullPointerException on Android

### ISSUE THREAD

**Issue by saket** [Anamorphosee/stacktrace-decoroutinator#14]
Hey @Anamorphosee, I'm running into this crash when trying to use SD on Android:

```
Caused by: java.lang.NullPointerException: it must not be null
        at dev.reformator.stacktracedecoroutinator.runtime.DecoroutinatorRuntime.load(runtime-android.kt:38)
        at dev.reformator.stacktracedecoroutinator.runtime.DecoroutinatorRuntime.load$default(runtime-android.kt:24)
```

The android artifact isn't an AAR so I wasn't able to step into the sources to debug what exactly is null. I was testing on Android 13.

**Comment by Anamorphosee** [comment]
Hi, @saket.
Could you please check if there is a file `decoroutinatorBaseContinuation.dex` in your APK?
And how do you declare a dependency on SD?

It's an AAR artifact https://repo1.maven.org/maven2/dev/reformator/stacktracedecoroutinator/stacktrace-decoroutinator-android/2.3.3/stacktrace-decoroutinator-android-2.3.3.aar

**Comment by astuetz** [comment]
Hi, I'm running into the same problem. I included the dependency as described on your readme for Android. Also there's no `decoroutinatorBaseContinuation.dex` inside the apk.

**Comment by Anamorphosee** [comment]
@astuetz Hi, maybe ProGuard deletes the file `decoroutinatorBaseContinuation.dex` in build time. Could you please check, if the file present if you build with
```
shrinkResources false
minifyEnabled false
```
?

**Comment by saket** [comment]
@Anamorphosee this is happening in debug builds where code minification isn't enabled

**Comment by Anamorphosee** [comment]
Fixed in 2.3.8. @saket Could you check please?

**Comment by saket** [comment]
Thanks, that was quick. I'll try it out and report back!

**Comment by saket** [comment]
Your fix works, but I'm now running into https://github.com/Anamorphosee/stacktrace-decoroutinator/issues/23 🙂.
