### ISSUE TITLE
Provide no-op variant for android builds

### ISSUE THREAD

**Issue by jakoss** [Anamorphosee/stacktrace-decoroutinator#2]
Great library! 

Have you considered creating no-op version of it so we can do 
```kotlin
debugImplementation("realVersion") 
releaseImplementation("noopVersion")
```

It's pretty standard practice on android to avoid bringing unnecessary libraries to release build

**Comment by Anamorphosee** [comment]
Released in `2.2.0`. No-op dependency is `stacktrace-decoroutinator-noop`.

Please pay attention on small inconsistency between version `2.1.0` and `2.2.0`: now method `DecoroutinatorRuntime.load()` should be called manually. See details in #3.
