### ISSUE TITLE
Application class implementation is redundant

### ISSUE THREAD

**Issue by dant3** [Anamorphosee/stacktrace-decoroutinator#3]
It's not really convenient that you bring the default application impl with your android library. It's very rare for real-life project to don't have a chosen way of init already, usually via it's own Application class or via jetpack [app-startup](https://developer.android.com/topic/libraries/app-startup).

Not only it's unnecessary and mostly useless piece of code, it also forces usage of tricks then this library is used in your manifest - adding obscure ```tools:replace="android:name"``` in app AndroidManifest.xml

**Comment by dant3** [comment]
you can also look at other libraries which require init as an example, such as [Stetho](http://facebook.github.io/stetho/) or [AppCenter SDK](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android#41-add-the-start-method)

**Comment by Anamorphosee** [comment]
Released in `2.2.0`.
