### ISSUE TITLE
Make minSdk lower in android library

### ISSUE THREAD

**Issue by dant3** [Anamorphosee/stacktrace-decoroutinator#4]
minSdk = 26 covers 80% of the devices according to play market stats. While it might work for some projects, it will not work for others. Is there a specific reason why it has to be 26? Looking at the code, I guess it can be easily lowered to something like 21 which would make this library easier to use.

Currently you have to add a pesky 
```
    <uses-sdk
        android:minSdkVersion="24"
        tools:overrideLibrary="dev.reformator.stacktracedecoroutinator"
        />
```

in order to use this library in android project which needs lower minSdk

**Comment by Anamorphosee** [comment]
minSdkVersion was made 26 for a reason:
Classes that the SD generates use the [MethodHandles API](https://developer.android.com/reference/java/lang/invoke/MethodHandle), which requires API 26.

It's possible not to use MethodHandles, but it will require significantly more generated classes.

**Comment by dant3** [comment]
Alright. So it means you can't get away with the override, which makes #2 even more valuable then.
